### ISSUE TITLE
error: but does not contain package github.com/atc0005/go-teams-notify/v2/adaptivecard

### ISSUE THREAD

**Issue by maxisam** [atc0005/go-teams-notify#185]
Hi I am new to Golang (like a week)

I got an error like 

`[but does not contain package github.com/atc0005/go-teams-notify/v2/adaptivecard](go: module github.com/atc0005/go-teams-notify/v2@upgrade found (v2.6.1), but does not contain package github.com/atc0005/go-teams-notify/v2/adaptivecard)`

Could you help me? Thanks!

**Comment by maxisam** [comment]
Never mind, I figured out. adaptivecard is an alpha feature.

**Comment by atc0005** [comment]
> Never mind, I figured out. adaptivecard is an alpha feature.

Hi @maxisam,

I've probably been too cautious with introducing changes since the v2.6.1 "stable" release. This includes refactoring work and the adaptivecard package that you referenced.

If you want to test the package/functionality now, you can modify your go.mod file to reference the latest pre-release tag.

Example available here:

https://github.com/atc0005/send2teams/blob/d536857c14c134416b5ed1c1ad2532ad6d353f06/go.mod#L16

```
module github.com/atc0005/send2teams

go 1.19

require github.com/atc0005/go-teams-notify/v2 v2.7.0-alpha.6
```

Feedback is welcome.

Please feel free to chime in here with general feedback:

https://github.com/atc0005/go-teams-notify/discussions/181

or start a new thread if you have more specific feedback.

Thanks in advance!
