### ISSUE TITLE
Setting `IsSubtle` and other fields

### ISSUE THREAD

**Issue by codello** [atc0005/go-teams-notify#254]
Hello, I'm just trying out this project for dynamically creating and sending adaptive cards. I was wondering if there is currently any way to set the `isSubtle` property on `TextBlock` elements (or other elements for that matter). It also seems to me there are some other properties from the [schema](https://adaptivecards.io/explorer/TextBlock.html) that currently cannot be set (e.g. `horizontalAlignment`).

Is there a generic way of setting these fields? Do you accept PRs for adding new field to the `Element` struct?

**Comment by atc0005** [comment]
Hi @codello,

> I was wondering if there is currently any way to set the isSubtle property on TextBlock elements (or other elements for that matter).

Not at the moment.

> It also seems to me there are some other properties from the [schema](https://adaptivecards.io/explorer/TextBlock.html) that currently cannot be set (e.g. horizontalAlignment).

That is correct. This library has grown somewhat organically with support added as dependent projects have found a need for it. There is still much to do.

> Is there a generic way of setting these fields? 

Not that I am aware of.

> Do you accept PRs for adding new field to the Element struct?

Sure. Thank you for your interest.

For better or worse, the current design treats the Element type as a starting point for more specific types (e.g., `TextBlock`). Constructors are provided for creating the most common types with client code responsible for creating other types where constructors are not provided.

For example, the `NewTextBlockCard` function creates an `Element` with common fields set and ready for further specialization by client code:

https://github.com/atc0005/go-teams-notify/blob/f941266eb2e3c363372616a3c0ef0b79e79a22bb/adaptivecard/adaptivecard.go#L2525-L2535

Validation (unless overridden) is applied to ensure that fields are set with valid values. Depending on what fields you are looking to add we may need to expand the validation checks to cover those fields.

The current design is somewhat brittle. A future v3 redesign would likely involve refactoring so that every element would be standalone and any fields present would already be valid for that type; fields would not be exposed for types which would not support them (in contrast to what is currently occurring).

**Comment by codello** [comment]
Thank you for the answer and for the explanation on the design. I will create a PR for `IsSubtle` and the `HorizontalAlignment` for now, because that's what I'm currently missing.

I think your approach to a v3 makes sense. I like the current composability of the `Element` type, that makes it easy to define cards in code like
```go
e := Element{
    Type: TypeElementContainer
    Items: {{
        Type: "…"
        ...
    }}
}
```

But this kind of composability could probably be achieved by designing elements around an `Element` interface similar to this:
```go
type Element interface {
    Type() string
    Validate() error
}
```
or something along those lines…
